[tools]
postgres = "16"

[env]
MIX_ENV = "dev"
DATABASE_URL = { required = "For local development update mise.local.toml, e.g., postgresql://localhost/qot_dev" }
FRONTEND_URL = { required = "For local env update mise.local.toml, e.g., http://localhost:5173" }
JWT_SECRET_KEY = { required = "Secret key for signing JWT tokens" }
RESEND_API_KEY = { required = "API key from resend.com" }
