[package]
name = "notes"
version = "0.1.0"
edition = "2021"

[dependencies]
automerge = "0.6"
autosurgeon = { version = "0.8", features = ["uuid"] }
uuid = { version = "1.0", features = ["v7"] }

[lib]
crate-type = ["lib"]
